
import sys
import os
import ctypes
import numpy as np
import circle

# Load the shared library
lib_path = os.path.join(os.path.dirname(__file__), 'libquantize.so')
if not os.path.exists(lib_path):
    print(f"Error: {lib_path} not found. Please compile it first.")
    sys.exit(1)

lib = ctypes.CDLL(lib_path)
lib.circle_quantize_q4_0.argtypes = [ctypes.POINTER(ctypes.c_float), ctypes.c_void_p, ctypes.c_int64]
lib.circle_quantize_q4_0.restype = None

def quantize_tensor(model, subgraph, tensor_index):
    tensor = subgraph.tensors[tensor_index]
    buffer = model.buffers[tensor.buffer]
    
    if tensor.type != circle.TensorType.FLOAT32:
        return False
    
    if buffer.data is None:
        return False

    # Get float data
    data_bytes = buffer.data.tobytes()
    data_float = np.frombuffer(data_bytes, dtype=np.float32)
    n_elements = data_float.size
    
    # Check if divisible by 32 (block size for Q4_0)
    if n_elements % 32 != 0:
        print(f"Skipping tensor {tensor.name}: size {n_elements} not divisible by 32")
        return False

    # Allocate output buffer
    # Q4_0: 32 floats -> 1 block (18 bytes)
    # Size = n_elements / 32 * 18
    n_blocks = n_elements // 32
    out_size = n_blocks * 18
    out_data = ctypes.create_string_buffer(out_size)
    
    # Call C++ function
    src_ptr = data_float.ctypes.data_as(ctypes.POINTER(ctypes.c_float))
    lib.quantize_q4_0(src_ptr, out_data, n_elements)
    
    # Update buffer
    # We need to create a new buffer or update existing one?
    # Circle buffers are shared? Usually not for weights.
    # But to be safe, let's update the existing buffer object if it's not shared, 
    # or check if we should create a new one. 
    # For simplicity, we update the buffer in place (replace data).
    # But wait, buffer.data is a ubyte vector.
    
    # Convert out_data to numpy uint8 array
    new_data_np = np.frombuffer(out_data, dtype=np.uint8)
    buffer.data = new_data_np
    
    # Update tensor type
    tensor.type = circle.TensorType.GGML_Q4_0
    
    print(f"Quantized tensor {tensor.name} (idx {tensor_index}): {n_elements} floats -> {out_size} bytes")
    return True

def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input_circle> <output_circle>")
        sys.exit(1)
        
    input_path = sys.argv[1]
    output_path = sys.argv[2]
    
    with open(input_path, 'rb') as f:
        buf = f.read()
        
    model = circle.Model.GetRootAsModel(buf, 0)
    # We need to modify the model. FlatBuffers python API is read-only for the object wrapper.
    # We need to use the object API or rebuild the flatbuffer.
    # The `circle` module generated by `flatc` usually has an object API if generated with `--python`.
    # However, the `circle.py` we saw earlier seems to be the generated code.
    # Let's check if it has `InitFromObj` or similar, or if we need to use the `T` classes (ModelT, etc).
    # The `circle.py` showed `ModelT` class?
    # Yes, I saw `class TensorType(object):` and `class QuantizationDetails(object):`.
    # I also saw `class ModelT(object):` in the `reshape.fc_weight.py` imports: `from circle import (TensorT, ... ModelT ...)`
    # So we can unpack to object, modify, and pack.
    
    model_t = circle.ModelT.InitFromObj(model)
    
    quantized_count = 0
    
    for subgraph in model_t.subgraphs:
        for op in subgraph.operators:
            opcode_index = op.opcodeIndex
            opcode = model_t.operatorCodes[opcode_index]
            builtin_code = opcode.builtinCode
            
            target_tensor_indices = []
            
            if builtin_code == circle.BuiltinOperator.FULLY_CONNECTED:
                # Weights are at index 1
                if len(op.inputs) > 1:
                    target_tensor_indices.append(op.inputs[1])
            elif builtin_code == circle.BuiltinOperator.GATHER:
                # Params are at index 0
                if len(op.inputs) > 0:
                    target_tensor_indices.append(op.inputs[0])
            
            for tensor_idx in target_tensor_indices:
                if tensor_idx == -1: continue
                
                # Check if it was already quantized (shared weights)
                tensor = subgraph.tensors[tensor_idx]
                if tensor.type == circle.TensorType.GGML_Q4_0:
                    continue
                
                # Quantize
                # We need to pass the model_t to access buffers
                # buffer index is in tensor.buffer
                buffer = model_t.buffers[tensor.buffer]
                
                # Check conditions
                if tensor.type != circle.TensorType.FLOAT32:
                    continue
                if buffer.data is None: # Not a constant
                    continue
                    
                # Quantize logic inline or helper
                # Helper needs to handle ModelT objects
                
                # Get float data
                # buffer.data is a list of ints (uint8) in the object API?
                # Let's assume it is a list or numpy array.
                # In FlatBuffers object API, vector fields are usually lists.
                data_bytes = bytes(buffer.data)
                data_float = np.frombuffer(data_bytes, dtype=np.float32)
                n_elements = data_float.size
                
                if n_elements % 32 != 0:
                    # print(f"Skipping {tensor.name}: size {n_elements} not divisible by 32")
                    continue
                    
                n_blocks = n_elements // 32
                out_size = n_blocks * 18
                out_data = ctypes.create_string_buffer(out_size)
                
                src_ptr = data_float.ctypes.data_as(ctypes.POINTER(ctypes.c_float))
                lib.circle_quantize_q4_0(src_ptr, out_data, n_elements)
                
                # Update buffer
                new_data_np = np.frombuffer(out_data, dtype=np.uint8)
                buffer.data = new_data_np.tolist() # Convert back to list for FB object
                
                # Update tensor type
                tensor.type = circle.TensorType.GGML_Q4_0
                quantized_count += 1
                print(f"Quantized {tensor.name}")

    if quantized_count > 0:
        print(f"Quantized {quantized_count} tensors.")
        # Save
        builder = circle.flatbuffers.Builder(1024)
        model_offset = model_t.Pack(builder)
        builder.Finish(model_offset, file_identifier=b'CIR0')
        buf = builder.Output()
        with open(output_path, 'wb') as f:
            f.write(buf)
    else:
        print("No tensors quantized.")

if __name__ == "__main__":
    main()
